### ISSUE TITLE
Remove Gulp from the equation

### ISSUE THREAD

**Issue by kaguillera** [kaguillera/newspipeline#7]
This ticket is a major ticket for the turning of the entire project. The intension now is to totally remove the dependance on Gulp and the controller of the entire framework. as such any functionality that depend or uses a gulp/node library will be replace with an equivalent python library. Thus the following steps and hopefully commits.

**Tasks**  _(According to the `gulpfile.babel.js` file)_
- [x] Clean - The resetting of the project. ([commit](00eeeee15260ba93c74eee1ef9e059418463279f))
- [x] Pages - convert markdown into HTML ([commit](beb9dad76def474d23678b0d00112ad77ab03ce9))
- [x] Sass - Produce CSS from the Sass ([commit](fbf29f351e51db0468e4207a666f1396946cc801))
- [ ] Images - Compress images (commit - TBA)
- [ ] Inline - Imbed the CSS into the HTML tags (commit - TBA)
- [ ] Serve - Serve the produced HTML and watch for changes (commit - TBA)

**Componenets** _(In order of tasks again from `gulpfile.babel.js`)_ 
- [x] Create Makefile to clean/reset project (i.e. delete `dist` directory)
- [x] Replace Panine and Handlebars with Jinga2 ( converting the markdown to HTML)
- [x] Replace gulp-sass with libsass-python
- [ ] Replace gulp-imagemin with jinga-assets-compressor
- [ ] Replace gulp-inline-css with libsass-python !?!?
- [x] Replace BrowserSync with python-livereload
- [ ] Replace Gulp with Makefile (entirely)

**NB** - Jinga-assets-compressor may also be used to do the inline of css and can be used with jinga (obviously, hence the name)

**Comment by kaguillera** [comment]
I am trying to mimic all of the functionality that the gulp controller provide and give the control to Makefile and have python scripts perform the functionality. To this end I am also looking at implementing the following aggregate functionalities:
- [x] `start` - which calls the default gulp command in `gulpfile.babel.js` (e0db6f97b256959a895709504a0b60a63ba0a3a6)
- [ ] `build` - which builds the production gulp command
- [ ] `zip` - which zips the production version of the emails produced. 
- [ ] `litmus` - May not implement this unless I get a request or PR for it. Not a priority at this time.

**Comment by kaguillera** [comment]
It took me the last 3 hours to realize that `jinja-assets-compressor` is for compiling/compressing/minifying of css and js files and not images. not sure if I need this so I will undo all of the changes that I have made. 
👎  wasted so much time.
